name: Deploy

on:
  push:
    branches: ['main']
    paths-ignore:
      - '**.md'
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: schedule-planner

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_RBAC_CREDENTIALS }}

      - name: 'Set up Go'
        uses: actions/setup-go@v3
        with:
          go-version: 1.22

      - name: Build
        run: |
          mkdir -p ./out
          GOOS=windows GOARCH=amd64 go build -o ./out/main
          cp -r ./web ./static

      - name: 'Deploy to Azure'
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
